### ISSUE TITLE
Error Occured while loading the Extension.

### ISSUE THREAD

**Issue by Harshitt69** [gauravnarwani97/Trishul#1]
This didn't install and the burp window threw an error which I'm mentioning below.

**java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.c2p.<init>(Unknown Source)
	at burp.cvi.a(Unknown Source)
	at burp.cl1.lambda$panelLoaded$0(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)**

**Comment by gauravnarwani97** [comment]
Hey Harshitt,
This is the issue with your Jython jar file. Make sure you have given the correct path to the jar file you downloaded from Jython Link mentioned in the Installation step #2. You can do that by chaniging the location of Jython Standalone Jar in Options Tab under Extender.

**Comment by gauravnarwani97** [comment]
You would face similar issue when installing other Bapps because of the Jython misconfiguration. 
Please let me know if you have solved it so we can close the issue.

**Comment by Harshitt69** [comment]
Hey Gaurav,
I tried all possible ways which I could. The jython file has been downloaded from the given link itself.
I crosschecked the path mentioned, that too was correct. I am still working on the issue.

**Comment by Harshitt69** [comment]
The Issue has been resolved. The problem was may be with the default java version of my system I guess. I updated everything and it installed.

Thank You.
